# CI de Nível 01 - Disparo Manal atráves de clique

# nome da pipeline
name: "Execução Manual"

# gatilhis / triigers - regrasd de ssisparo
# gatilho manual = workflow _dispath
on:
  workflow_dispatch:

# tarefas dentro da pipeline = jobs
jobs:
  # nome do job
  e2e-tests:

    # passos do job
    runs-on: ubuntu-latest

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/checkout@v4
        with: 
            node-version: 24.x

      # 
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Brwsers do Playwright
        run: yarn playwright install 

      - name: Executandoos testes e2e
        run: yarn run e2e



