name: Pipeline de Testes E2E (Self Hosted)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: self-hosted 

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências
        run: yarn

      - name: Instalar browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Executar testes E2E
        run: yarn run e2e