name: Pipeline de Testes E2E (Self Hosted)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências
        run: yarn install --frozen-lockfile

      - name: Verificando Browsers do Playwright
        run: yarn playwright install

      - name: Executando testes e2e
        run: yarn run e2e