name: Pipeline de Testes E2E (Self Hosted)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: self-hosted 
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar um comando de teste
        run: echo "Olá! Estou rodando de forma isolada dentro do Docker do meu PC!"
