name: Pipeline de Testes E2E (Self Hosted)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: self-hosted 
    
    steps:
      - name: Clone do Projeto
        uses: actions/checkout@v4

      - name: Instalar Depedências
        run: npm install --legacy-peer-deps

      - name: Executar os testes e2e
        shell: cmd
        env:
          DEBUG: pw:browser*
        run: nnpx.cmd playwright test
